name: Build and Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++

      - name: Configure with CMake Preset
        run: cmake --preset linux-gcc

      - name: Build project
        run: cmake --build build/linux-gcc --config Release

      - name: Run tests
        run: ctest --preset core-test -C Release
