name: Build and Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure with CMake Preset
        run: cmake --preset linux

      - name: Build project
        run: cmake --build build/linux --config Release

      - name: Run tests
        run: ctest --preset core-test -C Release
