name: Build and Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++

      - name: Build and install Catch2 v3.5.2
        run: |
          git clone --branch v3.5.2 --depth 1 https://github.com/catchorg/Catch2.git
          cmake -S Catch2 -B Catch2/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/catch2-install
          cmake --build Catch2/build --target install

      - name: Configure with CMake Preset
        run: cmake --preset linux-gcc -DCatch2_DIR=${{ github.workspace }}/catch2-install/lib/cmake/Catch2

      - name: Build project
        run: cmake --build build/linux-gcc --config Release

      - name: Run tests
        run: ctest --preset core-test -C Release
