name: Build and Test (Windows)

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSVC to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake and Ninja using Chocolatey
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress -y
          choco install ninja --no-progress -y

      - name: Cache Catch2
        id: cache-catch2
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}\catch2-install
          key: catch2-3.5.2-${{ runner.os }}

      - name: Build and install Catch2 (if cache miss)
        if: steps.cache-catch2.outputs.cache-hit != 'true'
        run: |
          git clone --branch v3.5.2 --depth 1 https://github.com/catchorg/Catch2.git
          cmake -S Catch2 -B Catch2/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\catch2-install"
          cmake --build Catch2/build --target install --config Release

      - name: Configure with CMake Preset
        run: >
          cmake --preset windows-msvc
          -DCatch2_DIR="${{ github.workspace }}\catch2-install\lib\cmake\Catch2"

      - name: Build project
        run: cmake --build build/windows-msvc --config Release

      - name: Run tests
        run: ctest --preset core-test --test-dir build/windows-msvc -C Release
